### PR TITLE
Revert "Merge pull request #169 from yast/netdev_fix_master"

### PR DESCRIPTION
**Pull request by gabi2**
This change is not wanted anymore as the root of the issue has been fixed in systemd already, see https://bugzilla.novell.com/show_bug.cgi?id=949683#c28

This reverts commit deefce05a32773247b13253d2daf6850800bc838, reversing
changes made to e5979fb5f30ec3d40544c0f21fd8bee84e7912de.

### TODO

- [ ] Fix version and changes

### CODE REVIEW

**Comment by lslezak** [comment]
Um, for me it's not clear why the commit is reverted. What's the reason for the revert?

**Comment by gabi2** [comment]
see https://bugzilla.novell.com/show_bug.cgi?id=949683#c28

**Comment by lslezak** [comment]
Ok, it's not needed as it was fixed in systemd...

The problem is that the package has been already submitted to Factory (https://build.opensuse.org/package/view_file/openSUSE:Factory/yast2-storage/yast2-storage.changes?expand=1). I guess version downgrade would make some troubles, `zypper up` would not install the newer package...

We cannot simply revert the commit. We have to **increase** the version number and **add** a new changelog entry describing the removal, the old entry should be kept...

**Comment by kobliha** [comment]
I've updated the PR description.

**Comment by gabi2** [comment]
You are right, the old changelog is needed and a new one about reverting and increase of version - done.

**Comment by imobach** [comment]
LGTM

**Pull request merged**
