### PR TITLE
Move check about PReP boot needed to Partitions module

### PR DESCRIPTION
**Pull request by imobach**
This is a minor refactoring [proposed by @kobliha](https://github.com/yast/yast-storage/pull/154#discussion_r39385283).

### CODE REVIEW

**Comment by aschnell** [comment]
Having NeedPrep and prep_boot_needed? is confusing. When should which function be used? Clarification from PPC team seems necessary.

**Comment by imobach** [comment]
@aschnell I guess you meant `PrepBoot` (as I don't see any `NeedPrep` method). Or maybe `NeedBoot`?

I guess that `PrepBoot` determines whether the system should boot from a *PRep/CHRP* partition. And the intention behind `prep_boot_needed?` is to check whether is mandatory to have a *PReP/CHRP* boot partition (when as far as I know, it's not mandatory for iSeries).

@k0da: could you help us to clarify this, please?

**Comment by kobliha** [comment]
@imobach That's the problem of undocumented API, we have to guess. Or could you find the docu? PLS, when you find out, add the API docu to at least that method :) thanks in advance

**Comment by k0da** [comment]
I wouldn't bother with iSeries. There is no dedicated hardware for iSeries, all runs on Power

**Comment by imobach** [comment]
@k0da So we're proposing handling the iSeries in the same way as we handle any other PPC, isn't it (so PReP partition will be mandatory)?

**Comment by kobliha** [comment]
The code was there for some reason. That's why we have comments and commit messages and Bugzilla and FATE. Please keep the same functionality as before unless we have a reason to remove it. We are JUST before RC1 and we can't afford losing functionality now.

**Comment by kobliha** [comment]
Although there might be no dedicated hardware, Yast code contains this at least 13-times, see https://github.com/search?utf8=%E2%9C%93&q=board_iseries+user%3Ayast&type=Code&ref=searchresults

**Comment by imobach** [comment]
@kobliha Yes, it makes sense. So back to the original question :). These are my guesses:

* PrepBoot determines whether the type of the boot partition should be 0x41 PReP/CHRP.
* For iSeries, this boot partition is not mandatory (as [stated here](https://github.com/yast/yast-storage/blob/master/src/include/partitioning/custom_part_check_generated.rb#L372)).

@k0da Is that correct? Thanks!

**Comment by aschnell** [comment]
If we don't have to support iSeries anymore please make a feature request to drop the support. Otherwise more and more obsolete code piles up and causes work as can be seen here.

**Comment by k0da** [comment]
@imobach sorry, I don't know how iSeries boots

**Comment by imobach** [comment]
@aschnell @kobliha Taking a look to [iSeries: Linux in a guest partition](http://publib.boulder.ibm.com/iseries/v5r2/ic2924/info/rzalm/rzalm.pdf), the PReP partition is not mandatory for iSeries. You have different options to boot the system.

So for me: `PrepBoot` determines whether the system should boot from a PRep/CHRP partition and `prep_boot_needed?` checks whether is mandatory to have a PReP/CHRP boot partition.

**Comment by kobliha** [comment]
LGTM (from non-storage-expert POV)

**Comment by aschnell** [comment]
LGTM, although clarification from PPC team is missing.

**Comment by imobach** [comment]
Thanks to all!

**Pull request merged**
