### PR TITLE
Replace references to /var/adm/fillup-templates with new %_fillupdir …

### PR DESCRIPTION
**Pull request by sysrich**
…macro (boo#1069468)

### CODE REVIEW

**Comment by sysrich** [comment]
Ping - this PR is going to be required for any future yast-storage submission to be acceptable for SLE 15, Leap 15, or Tumbleweed, as /var/adm/fillup-templates is now a blacklisted path

**Comment by ancorgs** [comment]
I just restart travis to see if we can merge this. Anyways, if the targets are SLE 15, Leap 15 and TW this could be less than urgent. SLE15 and Leap15 don't include yast-storage anymore (replaced by yast-storage-ng). And the plan is to also drop yast-storage from TW in a matter of days, weeks at most.

**Comment by imobachgs** [comment]
I've built this package manually and it works just fine. So I guess we could skip Travis and leave Jenkins to stop it if something goes wrong.

**Comment by ancorgs** [comment]
@imobachgs Makes sense. I already suspected the problem (the one visible in travis, at least) was our docker image being based on libstorage-ng. I guess it will build fine if the system running the tests is based on libstorage instead of libstorage-nb. So let's move forward.

**Pull request merged**
