### PR TITLE
Backport LVM fix to SLE-12-GA

### PR DESCRIPTION
**Pull request by imobach**
Backport of the LVM fix to SLE-12-GA (bsc#944492).

### CODE REVIEW

**Comment by aschnell** [comment]
Why? The "forgets LVM" bug does not exist on SLE12 GA.

**Comment by imobach** [comment]
@aschnell It was introduced by myself (I backported the 'fix' to SLE-12-GA). But we didn't release a new version of yast2-storage.

**Comment by aschnell** [comment]
I see. Too much back porting in the first place.

**Comment by imobach** [comment]
@aschnell Ok. I can only backport the 'revert' of the offending commit if you prefer.

**Comment by aschnell** [comment]
Yes, minimal revert would be better since otherwise translations break.

**Comment by imobach** [comment]
@aschnell Ok. I'm closing this PR and I'll open a new one. Thanks.

**Pull request closed without merging**
