### PR TITLE
Add PowerNV support

### PR DESCRIPTION
**Pull request by k0da**
Fixes boo#970582

Signed-off-by: Dinar Valeev <dvaleev@suse.com>

### CODE REVIEW

**Comment by k0da** [comment]
I there a way to tell travis to pick specific libstorage version?

**Comment by k0da** [comment]
local rake osc:build succeedes here:
[  125s] 
[  125s] 		=== yast2-storage Summary ===
[  125s] 
[  125s] # of expected passes		35

**Comment by lslezak** [comment]
I'd suggest ignoring the Travis failure for now, if the local osc build pasess then it's OK IMHO. I'll check why it fails at Travis but it will take some time as Travis debugging is difficult...

**Comment by k0da** [comment]
ping

**Comment by shundhammer** [comment]
LGTM

**Pull request merged**
